<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <!--<GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.6.133" />-->
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.36" />
    <PackageVersion Include="NServiceBus.Extensions.Hosting" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.1" />
  </ItemGroup>

</Project>
